name: loginsignuppages
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  dio: ^5.3.3
  animated_text_kit: ^4.2.2
  awesome_dialog: ^3.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo.png'

flutter:

  uses-material-design: true

  assets:
    - assets/icons/chat.svg
    - assets/icons/login.svg
    - assets/icons/signup.svg
    - assets/icons/facebook.svg
    - assets/icons/google-plus.svg
    - assets/icons/twitter.svg
    - assets/images/
